name: Workflow z Wbudowaną Akcją

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Wyświetl Komunikat
      run: echo "Workflow działa!"

    - name: Ustaw Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Instalacja Zależności
      run: npm install
      
    - name: Ustaw Zmienne Środowiskowe
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Wyświetl Zmienne Środowiskowe
      run: |
        echo "API_KEY: $API_KEY"
        echo "SECRET_KEY: $SECRET_KEY"
